language: go
go:
  - 1.5.1
env:
  - GO15VENDOREXPERIMENT=1
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.cache/pip
    - $GOPATH/src/github.com/deis/helm/vendor
    - $HOME/virtualenv/python2.7
services:
  - postgresql
sudo: required
addons:
  - postgresql: "9.3"
before_install:
  - wget "https://github.com/Masterminds/glide/releases/download/0.7.1/glide-0.7.1-linux-amd64.tar.gz"
  - sudo tar -vxz -C /usr/local/bin --strip=1 -f glide-0.7.1-linux-amd64.tar.gz
  - go get github.com/golang/lint/golint
  - wget "http://ftp.debian.org/debian/pool/main/s/shellcheck/shellcheck_0.3.7-4_amd64.deb"
  - sudo dpkg -i shellcheck_0.3.7-4_amd64.deb
  - sudo pip install virtualenv
  - virtualenv $HOME/virtualenv/python2.7
  - source $HOME/virtualenv/python2.7/bin/activate
  - createdb -U postgres deis
install:
  - pip install -r controller/requirements.txt
  - pip install -r controller/dev_requirements.txt
  - GLIDE_HOME=/home/travis/.glide make -C client bootstrap
script:
  - make -C controller test
  - make -C client test
