apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-workflow
  labels:
    heritage: deis
spec:
  replicas: 1
  selector:
    name: deis-workflow
  template:
    metadata:
      labels:
        name: deis-workflow
    spec:
      containers:
      - name: deis-workflow
        image: 192.168.99.100:5000/deis/workflow:git-3b9ce13
        ports:
          - containerPort: 8000
