apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-workflow
  labels:
    heritage: deis
spec:
  replicas: 1
  selector:
    name: deis-workflow
  template:
    metadata:
      labels:
        name: deis-workflow
    spec:
      containers:
      - name: deis-workflow
        image: deis/workflow:latest
        env:
          - name: DEBUG
            value: "true"
        ports:
          - containerPort: 8000
